@FitnessAppBackend_HostAddress = https://localhost:7258
@JWTtoken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1NDY4ODk0MS0wNzgwLTQ2NDYtOWZhOC1iYmE2MjM3N2ZlNTMiLCJlbWFpbCI6InN0cmluZyIsIm5hbWUiOiJzdHJpbmciLCJleHAiOjE3ODI4NDE4MTksImlzcyI6IkZpdG5lc3NBcHBCYWNrZW5kIiwiYXVkIjoiRml0bmVzc0FwcFVzZXJzIn0.AU6lxXrw-ukrPQQoqAnTXuvp6P3bPdGbcI35omMgjMY

##User Registraion
POST {{FitnessAppBackend_HostAddress}}/api/User/register
Content-Type: application/json
{
"Name": "Berat",  
"Email": "beratahmetaj65@gmail.com",
"Password": "12345678"
}

### GET All Users
GET {{FitnessAppBackend_HostAddress}}/api/User/all
Authorization: Bearer {{JWTtoken}}

###



