// ─── Workout Routines Configuration ──────────────────────────────────────────
// Each routine has a list of exercises from the ExerciseDB API.
// gradient is used for the card background until real images are added.

export interface RoutineExercise {
  name: string;
  exerciseId: string;
  sets: number;
  reps: string;
  restSeconds: number;
  category: string;
  gifUrl: string | null;
  description?: string;
}

export interface WorkoutRoutine {
  id: string;
  name: string;
  emoji: string;
  description: string;
  duration: string; // estimated duration
  difficulty: "Beginner" | "Intermediate" | "Advanced";
  targetMuscles: string[];
  equipment: string[]; // e.g. ["Barbell", "Dumbbell", "Bench"]
  gradient: [string, string]; // card gradient colors (placeholder for images)
  exercises: RoutineExercise[];
}

// ─── Routines ────────────────────────────────────────────────────────────────

export const ROUTINES: WorkoutRoutine[] = [
  {
    id: "home_sweat",
    name: "Living Room Burner",
    emoji: "🔥",
    description: "No equipment, full body calorie crusher from your living room.",
    duration: "25 min",
    difficulty: "Intermediate",
    targetMuscles: ["Full Body", "Cardio"],
    equipment: ["Body weight"],
    gradient: ["#FF6B35", "#C62368"],
    exercises: [
      {
        name: "Burpees",
        exerciseId: "dK9394r",
        sets: 3,
        reps: "15",
        restSeconds: 45,
        category: "Cardio",
        gifUrl: "https://static.exercisedb.dev/media/dK9394r.gif",
      },
      {
        name: "Mountain Climbers",
        exerciseId: "RJgzwny",
        sets: 4,
        reps: "20 each",
        restSeconds: 30,
        category: "Cardio",
        gifUrl: "https://static.exercisedb.dev/media/RJgzwny.gif",
      },
      {
        name: "Close-grip Push-ups",
        exerciseId: "x6KpKpq",
        sets: 3,
        reps: "10-15",
        restSeconds: 60,
        category: "Chest",
        gifUrl: "https://static.exercisedb.dev/media/x6KpKpq.gif",
      },
      {
        name: "Walking Lunges",
        exerciseId: "IZVHb27",
        sets: 3,
        reps: "12 each leg",
        restSeconds: 45,
        category: "Legs",
        gifUrl: "https://static.exercisedb.dev/media/IZVHb27.gif",
      },
      {
        name: "Jumping Jacks (Astride)",
        exerciseId: "f9lVSSI",
        sets: 3,
        reps: "30",
        restSeconds: 30,
        category: "Cardio",
        gifUrl: "https://static.exercisedb.dev/media/f9lVSSI.gif",
      },
    ],
  },
  {
    id: "core_30day",
    name: "30-Day Core Shred",
    emoji: "🍫",
    description: "The ultimate ab routine for a shredded core and defined obliques.",
    duration: "15 min",
    difficulty: "Advanced",
    targetMuscles: ["Abs", "Obliques"],
    equipment: ["Gym mat", "Body weight"],
    gradient: ["#0093E9", "#80D0C7"],
    exercises: [
      {
        name: "Crunches",
        exerciseId: "TFqbd8t",
        sets: 3,
        reps: "20",
        restSeconds: 30,
        category: "Abs",
        gifUrl: "https://static.exercisedb.dev/media/TFqbd8t.gif",
      },
      {
        name: "Bicycle Crunches",
        exerciseId: "tZkGYZ9",
        sets: 3,
        reps: "15 each side",
        restSeconds: 30,
        category: "Obliques",
        gifUrl: "https://static.exercisedb.dev/media/tZkGYZ9.gif",
      },
      {
        name: "Leg Raises",
        exerciseId: "I3tsCnC",
        sets: 3,
        reps: "12",
        restSeconds: 40,
        category: "Abs",
        gifUrl: "https://static.exercisedb.dev/media/I3tsCnC.gif",
      },
      {
        name: "Flutter Kicks",
        exerciseId: "UVo2Qs2",
        sets: 3,
        reps: "20 each leg",
        restSeconds: 30,
        category: "Abs",
        gifUrl: "https://static.exercisedb.dev/media/UVo2Qs2.gif",
      },
      {
        name: "Plank",
        exerciseId: "VBAWRPG",
        sets: 3,
        reps: "60 sec",
        restSeconds: 45,
        category: "Abs",
        gifUrl: "https://static.exercisedb.dev/media/VBAWRPG.gif",
      },
    ],
  },
  {
    id: "home_morning",
    name: "Morning Wake-Up Call",
    emoji: "☀️",
    description: "Quick 10-minute circuit to get your blood flowing and start the day right.",
    duration: "10 min",
    difficulty: "Beginner",
    targetMuscles: ["Full Body"],
    equipment: ["Body weight"],
    gradient: ["#FFD200", "#F7971E"],
    exercises: [
      {
        name: "Jumping Jacks (Astride)",
        exerciseId: "f9lVSSI",
        sets: 2,
        reps: "30",
        restSeconds: 30,
        category: "Cardio",
        gifUrl: "https://static.exercisedb.dev/media/f9lVSSI.gif",
      },
      {
        name: "High Knees",
        exerciseId: "ealLwvX",
        sets: 2,
        reps: "30 sec",
        restSeconds: 30,
        category: "Cardio",
        gifUrl: "https://static.exercisedb.dev/media/ealLwvX.gif",
      },
      {
        name: "Mountain Climbers",
        exerciseId: "RJgzwny",
        sets: 2,
        reps: "20",
        restSeconds: 30,
        category: "Cardio",
        gifUrl: "https://static.exercisedb.dev/media/RJgzwny.gif",
      },
      {
        name: "Tuck Crunches",
        exerciseId: "BMMolZ3",
        sets: 2,
        reps: "15",
        restSeconds: 40,
        category: "Abs",
        gifUrl: "https://static.exercisedb.dev/media/BMMolZ3.gif",
      },
    ],
  },
  {
    id: "apartment_legs",
    name: "Apartment Leg Day",
    emoji: "🦵",
    description: "Quiet, neighbor-friendly leg routine that still brings the burn.",
    duration: "20 min",
    difficulty: "Beginner",
    targetMuscles: ["Quads", "Glutes", "Calves"],
    equipment: ["Body weight"],
    gradient: ["#FA8BFF", "#2BD2FF"],
    exercises: [
      {
        name: "Walking Lunges",
        exerciseId: "IZVHb27",
        sets: 4,
        reps: "10 each leg",
        restSeconds: 45,
        category: "Legs",
        gifUrl: "https://static.exercisedb.dev/media/IZVHb27.gif",
      },
      {
        name: "Glute Bridge March",
        exerciseId: "GibBPPg",
        sets: 3,
        reps: "15",
        restSeconds: 45,
        category: "Glutes",
        gifUrl: "https://static.exercisedb.dev/media/GibBPPg.gif",
      },
      {
        name: "Curtsey Squat",
        exerciseId: "gUjqdei",
        sets: 3,
        reps: "12 each leg",
        restSeconds: 60,
        category: "Quads",
        gifUrl: "https://static.exercisedb.dev/media/gUjqdei.gif",
      },
      {
        name: "Standing Calf Raises",
        exerciseId: "8ozhUIZ",
        sets: 4,
        reps: "20",
        restSeconds: 30,
        category: "Calves",
        gifUrl: "https://static.exercisedb.dev/media/8ozhUIZ.gif",
      },
    ],
  },
  {
    id: "home_dumbbells",
    name: "Home Dumbbell Pump",
    emoji: "🏋️",
    description: "Just a pair of dumbbells needed for this upper body pump.",
    duration: "35 min",
    difficulty: "Intermediate",
    targetMuscles: ["Shoulders", "Chest", "Arms"],
    equipment: ["Dumbbell"],
    gradient: ["#4158D0", "#C850C0"],
    exercises: [
      {
        name: "Incline Dumbbell Press",
        exerciseId: "ns0SIbU",
        sets: 4,
        reps: "10-12",
        restSeconds: 60,
        category: "Chest",
        gifUrl: "https://static.exercisedb.dev/media/ns0SIbU.gif",
      },
      {
        name: "Dumbbell Shoulder Press",
        exerciseId: "A6wtbuL",
        sets: 4,
        reps: "10",
        restSeconds: 60,
        category: "Shoulders",
        gifUrl: "https://static.exercisedb.dev/media/A6wtbuL.gif",
      },
      {
        name: "Lateral Raises",
        exerciseId: "DsgkuIt",
        sets: 3,
        reps: "15",
        restSeconds: 45,
        category: "Shoulders",
        gifUrl: "https://static.exercisedb.dev/media/DsgkuIt.gif",
      },
      {
        name: "Hammer Curls",
        exerciseId: "slDvUAU",
        sets: 3,
        reps: "12",
        restSeconds: 45,
        category: "Biceps",
        gifUrl: "https://static.exercisedb.dev/media/slDvUAU.gif",
      },
      {
        name: "Dumbbell Pullover",
        exerciseId: "FSD6PGL",
        sets: 3,
        reps: "12",
        restSeconds: 60,
        category: "Chest",
        gifUrl: "https://static.exercisedb.dev/media/FSD6PGL.gif",
      },
    ],
  },
  {
    id: "full_body_gym",
    name: "Full Body Gym Starter",
    emoji: "ðŸ’ª",
    description: "Hit all major muscle groups with basic gym equipment. Perfect for beginners entering the gym.",
    duration: "45 min",
    difficulty: "Beginner",
    targetMuscles: ["Full Body"],
    equipment: ["Barbell", "Dumbbell", "Bench"],
    gradient: ["#FF416C", "#FF4B2B"],
    exercises: [
      {
        name: "Barbell Bench Press",
        exerciseId: "EIeI8Vf",
        sets: 4,
        reps: "8-10",
        restSeconds: 90,
        category: "Chest",
        gifUrl: "https://static.exercisedb.dev/media/EIeI8Vf.gif",
      },
      {
        name: "Dumbbell Deadlift",
        exerciseId: "nUwVh7b",
        sets: 4,
        reps: "10",
        restSeconds: 90,
        category: "Legs",
        gifUrl: "https://static.exercisedb.dev/media/nUwVh7b.gif",
      },
      {
        name: "Dumbbell Shoulder Press",
        exerciseId: "A6wtbuL",
        sets: 3,
        reps: "10-12",
        restSeconds: 60,
        category: "Shoulders",
        gifUrl: "https://static.exercisedb.dev/media/A6wtbuL.gif",
      },
    ],
  },
  {
    id: "cardio_mix",
    name: "Cardio Mix",
    emoji: "🏃‍♂️",
    description: "Get your heart rate up with a mix of gym cardio machines.",
    duration: "30 min",
    difficulty: "Beginner",
    targetMuscles: ["Cardio"],
    equipment: ["Cardio Machine"],
    gradient: ["#00B4DB", "#0083B0"],
    exercises: [
      {
        name: "Incline Treadmill",
        exerciseId: "rjiM4L3",
        sets: 1,
        reps: "10 min",
        restSeconds: 0,
        category: "Cardio",
        gifUrl: "https://static.exercisedb.dev/media/rjiM4L3.gif",
      },
      {
        name: "Elliptical cross trainer",
        exerciseId: "rjtuP6X",
        sets: 1,
        reps: "10 min",
        restSeconds: 0,
        category: "Cardio",
        gifUrl: "https://static.exercisedb.dev/media/rjtuP6X.gif",
      },
      {
        name: "Stationary bike",
        exerciseId: "H1PESYI",
        sets: 1,
        reps: "10 min",
        restSeconds: 0,
        category: "Cardio",
        gifUrl: "https://static.exercisedb.dev/media/H1PESYI.gif",
      },
    ],
  },
  {
    id: "quick_hiit",
    name: "Quick HIIT",
    emoji: "⚡",
    description: "A fast intense full-body high-intensity interval training session. No equipment needed.",
    duration: "15 min",
    difficulty: "Advanced",
    targetMuscles: ["Full Body", "Cardio"],
    equipment: ["Body weight"],
    gradient: ["#FDC830", "#F37335"],
    exercises: [
      {
        name: "Burpees",
        exerciseId: "dK9394r",
        sets: 3,
        reps: "30 sec",
        restSeconds: 15,
        category: "Cardio",
        gifUrl: "https://static.exercisedb.dev/media/dK9394r.gif",
      },
      {
        name: "High Knees",
        exerciseId: "ealLwvX",
        sets: 3,
        reps: "30 sec",
        restSeconds: 15,
        category: "Cardio",
        gifUrl: "https://static.exercisedb.dev/media/ealLwvX.gif",
      },
      {
        name: "Mountain Climbers",
        exerciseId: "RJgzwny",
        sets: 3,
        reps: "30 sec",
        restSeconds: 15,
        category: "Cardio",
        gifUrl: "https://static.exercisedb.dev/media/RJgzwny.gif",
      },
      {
        name: "Jumping Jacks",
        exerciseId: "f9lVSSI",
        sets: 3,
        reps: "30 sec",
        restSeconds: 15,
        category: "Cardio",
        gifUrl: "https://static.exercisedb.dev/media/f9lVSSI.gif",
      },
    ],
  },
  {
    id: "upper_body_builder",
    name: "Upper Body Builder",
    emoji: "💪",
    description: "Focus on chest, back, and arms using dumbbells.",
    duration: "40 min",
    difficulty: "Intermediate",
    targetMuscles: ["Chest", "Back", "Arms"],
    equipment: ["Dumbbell"],
    gradient: ["#3a7bd5", "#3a6073"],
    exercises: [
      {
        name: "Incline Dumbbell Press",
        exerciseId: "ns0SIbU",
        sets: 4,
        reps: "10-12",
        restSeconds: 60,
        category: "Chest",
        gifUrl: "https://static.exercisedb.dev/media/ns0SIbU.gif",
      },
      {
        name: "Dumbbell Pullover",
        exerciseId: "FSD6PGL",
        sets: 3,
        reps: "12",
        restSeconds: 60,
        category: "Chest",
        gifUrl: "https://static.exercisedb.dev/media/FSD6PGL.gif",
      },
      {
        name: "Hammer Curls",
        exerciseId: "slDvUAU",
        sets: 3,
        reps: "12",
        restSeconds: 45,
        category: "Biceps",
        gifUrl: "https://static.exercisedb.dev/media/slDvUAU.gif",
      },
      {
        name: "Bodyweight Kneeling Triceps Extension",
        exerciseId: "s0HKO2I",
        sets: 3,
        reps: "12-15",
        restSeconds: 45,
        category: "Triceps",
        gifUrl: "https://static.exercisedb.dev/media/s0HKO2I.gif",
      },
    ],
  },
  {
    id: "lower_body_power",
    name: "Lower Body Power",
    emoji: "🦵",
    description: "Build leg strength and power.",
    duration: "35 min",
    difficulty: "Intermediate",
    targetMuscles: ["Legs", "Glutes", "Calves"],
    equipment: ["Dumbbell", "Body weight"],
    gradient: ["#11998e", "#38ef7d"],
    exercises: [
      {
        name: "Dumbbell Deadlift",
        exerciseId: "nUwVh7b",
        sets: 4,
        reps: "10-12",
        restSeconds: 90,
        category: "Legs",
        gifUrl: "https://static.exercisedb.dev/media/nUwVh7b.gif",
      },
      {
        name: "Walking Lunges",
        exerciseId: "IZVHb27",
        sets: 4,
        reps: "12 each leg",
        restSeconds: 60,
        category: "Legs",
        gifUrl: "https://static.exercisedb.dev/media/IZVHb27.gif",
      },
      {
        name: "Glute Bridge March",
        exerciseId: "GibBPPg",
        sets: 3,
        reps: "15",
        restSeconds: 45,
        category: "Glutes",
        gifUrl: "https://static.exercisedb.dev/media/GibBPPg.gif",
      },
      {
        name: "Standing Calf Raises",
        exerciseId: "8ozhUIZ",
        sets: 4,
        reps: "20",
        restSeconds: 45,
        category: "Calves",
        gifUrl: "https://static.exercisedb.dev/media/8ozhUIZ.gif",
      },
    ],
  }
];
